"""Parent-only candidate integration for static coordinate score support."""
import json,hashlib,datetime,csv
from pathlib import Path
R=Path('/data/CoordExp/outputs/research/qwen3-vl-dense-enumeration/2026-09-19-coordinate-pair-readout');U=Path('research/experiments/2026-09-19-coordinate-pair-readout')
def bind(p):return dict(path=str(p.resolve()),sha256=hashlib.sha256(p.read_bytes()).hexdigest())
def main():
 d=json.loads((R/'reduction.json').read_text());v=json.loads((R/'verification.json').read_text());p=json.loads((R/'execution-plan.json').read_text());b=json.loads((R/'binding-verification.json').read_text());assert d==json.loads((R/'reduction-recheck.json').read_text());assert len(d['cells'])==v['cells']==66;assert sum(c['control_equal'] is True for c in d['cells'])==22;assert not b['unresolved']
 shards=[json.loads(x.read_text()) for x in (R/'runtime').rglob('shard-receipt.json')];assert len(shards)==9 and all(x['status']=='candidate_complete' for x in shards);cost={k:sum(x[k] for x in shards) for k in ['model_forwards','vision_forwards','gpu_seconds','tensor_bytes']};now=datetime.datetime.now(datetime.timezone.utc).isoformat()
 with (R/'outcomes.csv').open('w') as f:
  names=['boundary','policy','longest_exact_run','longest_near_run','all_pairs_exact','all_pairs_near','all_pairs_denominator','invalid_rows','malformed_openers','complete_rows','stop'];w=csv.DictWriter(f,fieldnames=names);w.writeheader()
  for c in d['cells']:w.writerow(dict(boundary=c['boundary_id'],policy=c['policy'],stop=c['stop'],**{k:c['metrics'][k] for k in names if k in c['metrics']}))
 science='Sparse continuing changes on logits0/1 are sufficient for sign23-like low numerical recurrence on both selected donut models, while removing that pair from sign23 loses the near-run1/zero-all-pairs outcome. Untied responds to only0; tied requires the pair among these tested supports. The pattern is case-specific, not a universal two-logit cause or physical recovery.'
 result=dict(status='INTEGRATED_CANDIDATE',acceptance='unreviewed_by_root',unit=U.name,created_at=now,scientific=science,technical='66/66 cells;22 exact original/sign23controls;17909steps independently reconstructed; wrong-support sensitivity passes.',cost=cost,cells=66,boundaries=11,images=6,failed_attempts=[],unsupported=[],live_jobs=[],limits=['Support magnitude intentionally differs; this is not a magnitude-matched test. Coefficients/sign23 unchanged.','Outcome-informed support/field selection, evaluated on all11 original failure boundaries; not a fresh cohort or population rate.','All generatedrows free; no first-row exclusion or forced token.','Near/all-pairs numerical boxes are not physicalowners; EOS/another pattern/less repetition is not recovery.','Changing0/1 output scores does not identify input embeddings, unique circuitry or training origin; legal0/1 values must not be treated as banned.','T/U is a model-package comparison; targetoutputs only, companions not interpreted.'],evidence=[bind(R/n) for n in ['execution-plan.json','reduction.json','verification.json','binding-verification.json','outcomes.csv','ARTIFACTS.md']])
 (R/'result.json').write_text(json.dumps(result,indent=2)+'\n')
 lines=['# Coordinate-pair readout support','',f'Candidate completed {now}; root acceptance pending.','',science,'','## Complete fixed panel','','All66 cells run from the original11 failure prefixes (six images), under original/sign23/only0/only1/pair01/except01. All22 controls reproduce accepted direction-study outputs exactly. Every generated row is free. CPU reduction is JSON-exact; all17,909 savedsteps satisfy score-support formulas, untouched-coordinate bit identity and actual greedy emission. A wrong-support CPU corruption is detected.','', 'Each entry below is **longest near-run / all-pairs near count / invalid rows / stop / complete rows**. R=32-row limit; E=EOS. Exact/all-pairs exact counts, native/alternate returns and row-level tokens remain in `reduction.json`/`outcomes.csv`; invalid literal rows are included in all-pairs comparisons.','', '| Boundary | Original | sign23 | only0 | only1 | pair01 | except01 |','|---|---|---|---|---|---|---|']
 for bid in dict.fromkeys(c['boundary_id'] for c in d['cells']):
  cc={c['policy']:c for c in d['cells'] if c['boundary_id']==bid}
  def fmt(pol):
   c=cc[pol];m=c['metrics'];return f"{m['longest_near_run']}/{m['all_pairs_near']}/{m['invalid_rows']}/{'E' if c['stop']=='eos' else 'R'}/{m['complete_rows']}"
  lines.append('| '+bid+' | '+' | '.join(fmt(pol) for pol in p['policies'])+' |')
 lines+=['','All cells have zero malformed openers and zero512-token caps. All-pairs counts are supplementary numerical accounting, not owner counts or independent trials.','', '## What the contrast establishes','','- **Tied donut:** pair01 gives near-run1 and zero near pairs, zero invalid rows, at32 rows; sign23 has the same numerical endpoints. Both singletons retain near-run17. except01 gives near-run15/169 near pairs at32 rows. This supports a joint sparse score contribution in this selected case, without an early-EOS explanation.','- **Untied donut:** pair01 and only0 each give near-run1/zero near pairs/zero invalidity, ending after30 and26 rows; sign23 ends after28. except01 retains near-run10/117 near pairs at32 rows. Termination remains a limit; no physical coverage claim. only0 first emits x1=13, whereas pair01 first emits1: the numerical result is not tied to emitting1 specifically.','- **only1:** all11 entire continuations are identical to original. This is a null for this frozen singleton operator on these routes, not general irrelevance of coordinate1.','- **Beyond donut:** untied5586 only0 produces near-run3/3 near pairs at31 rows thenEOS, versus original30/436; pair01 still has20/245 and except01 has12/157. Tied5586 pair01 and except01 both partly reduce runs. These support multiple/partial routes rather than one universal pair explanation.','- **Counterexamples retained:** both14038 and632 model pairs show no benefit from pair01, while sign23/except01 preserve their own beneficial or adverse behavior. Untied885 full sign23 worsens recurrence, while pair01 and except01 each reduce its numerical burden. Global-support effects are path-dependent and not a simple sum of per-support rollout benefits.','', '## Technical closure','',f"All8 GPUs used. {cost['model_forwards']:,} model forwards, {cost['vision_forwards']} vision passes, {cost['gpu_seconds']:.3f} allocated GPU-seconds ({cost['gpu_seconds']/3600:.3f} GPU-hours), {cost['tensor_bytes']:,} tensor bytes. No failed GPU attempt, retry, new arm or predecessor rewrite. All pilot/scaleout wrappers observed exit0; all owned jobs and the Luna-max child ended.271 source/artifact bindings verified with no unresolved gap.",'','The producer qualification fields named `...fp64` compare final-cast scores toFP64 formula values; they include cast residuals. Independent `verification.json` separately reconstructs pre-cast support identities and final-cast scores. The initial parent file-discovery pass found zero cells because the pilot was nested; discovery was corrected before gate release and all6 pilot cells checked, without GPU repetition.','', 'Root-owned catalog result registration is the only expected knowledge-check gap. Exact commands and artifacts: `'+str(R/'ARTIFACTS.md')+'`.','', '## Limits','']+[f'- {x}' for x in result['limits']]
 (U/'results.md').write_text('\n'.join(lines)+'\n');s=json.loads((U/'state.json').read_text());s.update(lifecycle='closed',evidence='unreviewed',state_as_of=now,disposition=science,result=str(U/'results.md'),state_source=str(U/'results.md'),next_action='Root independent acceptance; worker stops. No successor.');(U/'state.json').write_text(json.dumps(s,indent=2)+'\n');print(json.dumps(dict(result=str(R/'result.json'),cost=cost)))
if __name__=='__main__':main()
