extends: ./base.yaml

model:
  model: model_cache/models/Qwen/Qwen3-VL-2B-Instruct-coordexp

training:
  artifact_subdir: stage1_2b/ablation/coord_components/coord_token_hard_ce
  run_name: ablation_stage1_2b_coord_components_coord_token_hard_ce

custom:
  coord_soft_ce_w1:
    enabled: false
  bbox_geo:
    enabled: false
