"""Parent-only candidate integration from sealed saved-target evidence."""
import datetime,hashlib,json
from pathlib import Path
R=Path('/data/CoordExp/outputs/research/qwen3-vl-dense-enumeration/2026-09-18-readout-common-component')
U=Path('research/experiments/2026-09-18-readout-common-component')
def bind(p):return dict(path=str(p.resolve()),sha256=hashlib.sha256(p.read_bytes()).hexdigest())
def main():
 d=json.loads((R/'reduction.json').read_text());v=json.loads((R/'verification.json').read_text());cost=json.loads((R/'runtime/scaleout-completion-receipt-v2.json').read_text());bv=json.loads((R/'binding-verification.json').read_text())
 assert d==json.loads((R/'reduction-recheck.json').read_text()) and len(d['cells'])==v['cells']==100
 assert not bv['unresolved'] and cost['live_owned_producer_processes']==0
 assert all(x['original_source_overlap_equal'] is not False for x in v['reports'])
 now=datetime.datetime.now(datetime.timezone.utc).isoformat();f=[x for x in d['first_forks'] if x['policy']=='full']
 result=dict(status='INTEGRATED_CANDIDATE',acceptance='unreviewed_by_root',unit=U.name,created_at=now,technical='100/100 target continuations; independent CPU score reconstruction and saved-output reduction passed',scientific='Shared-only does not account for full normalization across this panel; centered-only also fails to reproduce it. Mixed/path-dependent numerical effects, no established physical recovery.',cells=100,boundaries=25,recurrent_boundaries=11,proxy_boundaries=14,images=7,summary=d['summary'],first_full_fork=dict(n=len(f),coordinate_to_coordinate=sum(x['same_state_shadows']['full']['flip_class']=='coordinate_to_coordinate' for x in f),shared_same_winner=sum(x['same_state_shadows']['shared']['top2'][0]['token_id']==x['actual_other_token'] for x in f),centered_same_winner=sum(x['same_state_shadows']['centered']['top2'][0]['token_id']==x['actual_other_token'] for x in f)),cost=cost['totals'],live_jobs=[],children='Luna-max feedback_luna completed; no live assigned child',mechanical_failure='One false padding guard rejected existing masked prompt padding before forward on affected cells. Preserved12 completed scaleout cells and all failures; corrected guard checks exact unpadded appended target suffix;84 remaining cells executed once. Initial launch-wrapper pre-model failure preserved. No tolerance/operator/history change.',limits=['Target outputs only; companion outputs uninterpretable. Original prompt masks/padding retained; appended target history has no padding.','Repeated boxes are numerical proxies, not verified physical duplicate owners; EOS or alternate recurrence is not recovery.','11 onset and14 pre-onset/nonrecurrent proxies on7 selected images are correlated, not prevalence samples.','Analytic centering convention, not a native module; interaction and generic decision-boundary/path effects remain.','Mature tied versus untied+axis is a model-package comparison, not untie-only causality.','Later histories differ; controlled shadow scores refer to one identical head state. No training-origin or deployment claim.'],evidence=[bind(R/n) for n in ['execution-plan.json','reduction.json','verification.json','binding-verification.json','ARTIFACTS.md']])
 (R/'result.json').write_text(json.dumps(result,indent=2)+'\n')
 lines=['# Readout common-component continuation','',f'Candidate completed {now}. Root acceptance pending.','',result['scientific'],'','## Evidence and contrasts','','The fixed25 original completed-row histories were each continued under original/full/shared/centered readout policies. All100 cells completed; no source history was edited. All25 fresh original controls match their saved native suffix overlap, and independent CPU reconstruction matches every saved shadow-coordinate score exactly across24,088 steps.','', 'At the first original-versus-full divergence, all25 changes are coordinate-to-coordinate. On that SAME original head state, shared-only selects the full winner in8/25 and centered-only in4/25. Neither component produces an exactly identical full-policy continuation on any of25 boundaries. Shared and centered trajectories coincide in6/25. These are finite selected-case comparisons, not independent trials.','', '| Model / boundary | Policy | n | Native near-return | Alternate repeat | EOS | Invalid rows |','|---|---|---:|---:|---:|---:|---:|']
 for s in d['summary']:lines.append(f"| {s['model']} / {s['kind']} | {s['policy']} | {s['n']} | {s['native_return']} | {s['alternate_repeat']} | {s['eos']} | {s['invalid_rows']} |")
 lines += ['','`healthy` in inherited IDs means a nonrecurrent/pre-onset proxy, not a globally healthy scene. Return/alternate/EOS categories overlap. All cells have zero malformed openers and zero512-token caps; other stops are32 completed target rows.','', '## Decision-bearing examples','','Untied417044 onset: longest near-run14 under original,1 under full (29 rows then EOS),15 under shared and15 under centered (both32-row stops). Full therefore has a distinct numerical effect here; this is not independently verified owner recovery. Untied7511 similarly changes11→3 under full with EOS, while either component yields17; full also creates one invalid row. Conversely untied632 worsens18→27 under full (shared25, centered23), and untied5586 stays at30 in every arm. Tied417044 improves17→6 under full, but shared25/centered20 worsen it. Thus neither a universal benefit nor a shared-only explanation survives.','', '## Technical and archival status','',result['mechanical_failure'],'','The suffix guard correction does not remove or alter native prompt padding/masks. All25 original-source replays pass after combining preserved and corrected outputs. The old producer-path hash is recovered by its exact prelaunch v1 snapshot;338 unique bindings checked with no unresolved gaps. The vacuous producer selfcheck decomposition expression is not relied upon: the independent verifier asserts the FP64 identity and all four saved-score formulas at every step.','',f"Cost: {cost['totals']['model_forwards']:,} batch forwards, {cost['totals']['vision_forwards']} vision passes, {cost['totals']['gpu_seconds']:.3f} allocated GPU-seconds ({cost['totals']['gpu_seconds']/3600:.3f} hours), {cost['totals']['tensor_bytes']:,} reported tensor bytes including repeated shard readout payloads. All8 GPUs were used for scaleout. All producers and the assigned Luna-max child ended. No cleanup, training, additional case or successor was performed.",'','## Reproduction and limits','','Knowledge checker: lifecycle/evidence axes valid; the sole remaining error is state result not catalogued. Catalog and broad routing are root-owned and intentionally unchanged pending acceptance.','',f"Artifacts and exact commands: `{R}/ARTIFACTS.md`. Full per-boundary metrics and150 paired comparisons: `reduction.json`; all68 observed original-policy first forks with four same-state shadow decisions are included. Model/config/input/prefix identities reside in plan, cell and shard receipts; raw target tokens and every-step head/coordinate tensors are retained.",'']+[f'- {x}' for x in result['limits']]
 (U/'results.md').write_text('\n'.join(lines)+'\n')
 state=json.loads((U/'state.json').read_text());state.update(lifecycle='closed',evidence='unreviewed',disposition=result['scientific'],state_as_of=now,result=str(U/'results.md'),state_source=str(U/'results.md'),next_action='Root independent acceptance; worker stops. No automatic successor.');(U/'state.json').write_text(json.dumps(state,indent=2)+'\n')
 print(json.dumps(dict(result=str(R/'result.json'),results=str(U/'results.md'))))
if __name__=='__main__':main()
