"""Parent-only integration for the fixed history/readout crossover."""
import json,hashlib,datetime
from pathlib import Path
R=Path('/data/CoordExp/outputs/research/qwen3-vl-dense-enumeration/2026-09-18-history-readout-crossover');U=Path('research/experiments/2026-09-18-history-readout-crossover')
def bind(p):return dict(path=str(p.resolve()),sha256=hashlib.sha256(p.read_bytes()).hexdigest())
def main():
 d=json.loads((R/'reduction.json').read_text());v=json.loads((R/'verification.json').read_text());plan=json.loads((R/'execution-plan.json').read_text());cost=json.loads((R/'runtime/scaleout-completion-receipt-v1.json').read_text())['aggregate_cost'];bv=json.loads((R/'binding-verification.json').read_text())
 assert d==json.loads((R/'reduction-recheck.json').read_text());assert len(d['cells'])==v['cells']==88;assert not bv['unresolved'];assert sum(c['unchanged_control'] for c in d['cells'])==44;assert all(c['saved_overlap_equal'] for c in d['cells'] if c['unchanged_control'])
 now=datetime.datetime.now(datetime.timezone.utc).isoformat()
 # Explicit row/role coordinates are derived from literal histories, never from predicted labels.
 roles=[]
 for c in d['cells']:
  h=next(h for h in plan['histories'] if h['boundary']['id']==c['boundary_id'] and h['cut']==c['cut'] and h['history_policy']==c['history_policy']);prefix=h['prefix_tokens'].copy();row=0;steps=[]
  for i,token in enumerate(c['tokens']):
   recent=next((len(prefix)-1-j for j,x in enumerate(reversed(prefix)) if x==151648),None);distance=len(prefix)-1-recent if recent is not None else None
   role=['x1','y1','x2','y2','box_end'][distance] if distance is not None and 0<=distance<=4 else 'row_boundary' if prefix[-1]==151649 else 'description_or_wrapper'
   steps.append(dict(free_offset=i,absolute_action_offset=len(prefix),free_row_index=row,role=role,token_id=token));prefix.append(token)
   if token==151649:row+=1
  roles.append(dict(cell=c['id'],steps=steps,row_index_semantics='Zero-based lexical box_end count; complete/invalid parsing is separately preserved in reduction.'))
 (R/'positions.json').write_text(json.dumps(roles,indent=2)+'\n')
 result=dict(status='INTEGRATED_CANDIDATE',acceptance='unreviewed_by_root',unit=U.name,created_at=now,technical='88/88 cells and44 unchanged-policy overlaps pass; CPU reconstruction covers21764 emitted steps',scientific='Persistence after withdrawal and efficacy of late normalization depend on model, scene and cut. Altered history can sustain low numerical recurrence in selected cases, but is not generally sufficient; ongoing readout and timing remain consequential.',cost=cost,unsupported=d['unsupported'],controls=44,boundaries=11,cuts=[4,8],live_jobs=[],limits=['Numerical recurrence is not verified physical identity or recovery. EOS/fewer rows can truncate repetition.','Histories differ in content, geometry, lengths/positions and covered context; across-history comparisons are conditional paths, not isolated owner memory.','Tied885 cut4 histories are identical; this group does not supply a distinct-history contrast.','11 selected boundaries and two dependent cuts are not independent population samples; T/U compares model packages, not untie-only.','Target outputs only; native companions are width-matched and remain outside the estimand.','No training-origin, policy promotion or universal circuit claim.'],failures='One pre-forward source-dictionary alias failure corrected with preserved snapshot; one stale receipt-binding seam corrected without repeating completed GPU cells. No scientific cell excluded or duplicated.',evidence=[bind(R/n) for n in ['execution-plan.json','reduction.json','verification.json','binding-verification.json','positions.json','ARTIFACTS.md']])
 (R/'result.json').write_text(json.dumps(result,indent=2)+'\n')
 lines=['# History/readout crossover','',f'Candidate completed {now}; root acceptance pending.','',result['scientific'],'','## Fixed evidence','','All11 failure boundaries supported actual original/full histories at both4 and8 complete rows:44 histories,88 fresh continuations. All44 unchanged-policy controls reproduce their saved overlap. Independent CPU reduction is JSON-exact and score reconstruction covers21,764 steps. Full supplied histories and raw/full same-state shadow decisions are retained; supplied rows receive no free-output credit.','', 'Below, each cell is **longest near-run / invalid rows / stop / free complete rows**. O=original, F=full normalization; the first letter is supplied-history policy and the second is future readout. R=32-row stop; E=EOS. Exact runs, native/alternate recurrence, crossing-cut events, malformed counts and every token remain in `reduction.json`.','', '| Boundary | Cut | OO | OF (late) | FO (withdrawal) | FF |','|---|---:|---|---|---|---|']
 for b in dict.fromkeys(c['boundary_id'] for c in d['cells']):
  for cut in [4,8]:
   cc={(c['history_policy'],c['future_policy']):c for c in d['cells'] if c['boundary_id']==b and c['cut']==cut}
   def fmt(h,f):
    c=cc[h,f];m=c['metrics'];return f"{m['longest_near_run']} / {m['invalid_rows']} / {'E' if c['stop']=='eos' else 'R' if c['stop']=='rows' else 'C'} / {m['complete_rows']}"
   lines.append('| '+b+' | '+str(cut)+' | '+' | '.join(fmt(h,f) for h,f in [('original','original'),('original','full'),('full','original'),('full','full')])+' |')
 lines += ['','## Bounded interpretation','','- **Untied417044:** withdrawal remains at longest near-run1 at both cuts, as does continued full normalization; late application also gives1 versus original10/13. EOS arrives after18–28 free rows depending on condition. This supports persistence through this altered history and a late numerical effect, not physical recovery.','- **Tied417044:** withdrawal gives16/8 versus continued-full2/1. Late application helps at cut4 (16→3) but worsens cut8 (12→20). This is a concrete readout/timing dependence and adverse example.','- **Untied7511:** normalized-history withdrawal gives1 versus continued-full3, but applying normalization after original histories worsens13→21 and17→23. Earlier route differences matter; late application cannot be substituted for the earlier history here.','- **Tied14038:** normalized histories retain shorter near-runs3 after withdrawal and continued normalization versus original8; all terminate and normalized-history outputs are shorter. Termination remains a competing explanation for reduced burden.','- **885/5586/632:** substantial recurrence remains, and normalization often lengthens it. These null/adverse cells are retained. Only tied885 cut4 has literally identical original/full supplied histories; other apparent similarities in summary metrics do not establish trajectory identity.','', 'A near-repeat triplet already spans the supplied/free boundary in55/88 cells. The reduction records supplied versus free indices explicitly. No cell hits512 tokens; all stops are EOS or32 completed rows. There are no malformed openers.','', '## Technical closure','',result['failures'],'',f"Cost including the zero-forward failed attempt: {cost['model_forwards_including_alias_failure']:,} batch forwards, {cost['gpu_seconds_including_alias_failure']:.3f} allocated GPU-seconds ({cost['gpu_seconds_including_alias_failure']/3600:.3f} GPU-hours), {cost['tensor_bytes_including_preserved_alias_artifact']:,} tensor bytes. Eight GPUs used; all owned jobs and Luna-max child completed.350 unique source/artifact bindings verified; old producer hashes are recovered by exact prelaunch snapshots. No accepted predecessor changed.",'', 'The sole expected knowledge-check gap is root-owned catalog result registration. Worker does not edit broad routing. Exact commands and artifact paths: `'+str(R/'ARTIFACTS.md')+'`.','', '## Limits','']+[f'- {x}' for x in result['limits']]
 (U/'results.md').write_text('\n'.join(lines)+'\n');state=json.loads((U/'state.json').read_text());state.update(lifecycle='closed',evidence='unreviewed',state_as_of=now,disposition=result['scientific'],result=str(U/'results.md'),state_source=str(U/'results.md'),next_action='Root independent acceptance; worker stopped, no successor.');(U/'state.json').write_text(json.dumps(state,indent=2)+'\n')
 print(json.dumps(dict(result=str(R/'result.json'),status='candidate')))
if __name__=='__main__':main()
