import json,hashlib,difflib
from pathlib import Path
base=Path('/data/CoordExp/outputs/research/qwen3-vl-dense-enumeration'); old=base/'2026-09-16-corner-loop-one-bin-control'; r=base/'2026-09-16-corner-loop-y1-one-bin-control'; r.mkdir(exist_ok=False)
def bind(p):return dict(path=str(p),sha256=hashlib.sha256(p.read_bytes()).hexdigest(),size_bytes=p.stat().st_size)
p=json.loads((old/'panel.json').read_text())
for b in p['sources']:assert bind(Path(b['path']))==b,b['path']
s=(old/'producer.py').read_text(); n=s.replace(str(old),str(r)).replace('One still-invalid y2 edit','One near-boundary y1 edit').replace("choices=['Y998']","choices=['Y1_998']")
(r/'producer.py').write_text(n);(r/'producer.diff').write_text(''.join(difflib.unified_diff(s.splitlines(True),n.splitlines(True),fromfile=str(old/'producer.py'),tofile=str(r/'producer.py'))))
from transformers import AutoTokenizer
t=AutoTokenizer.from_pretrained(p['config']['model']['base_model'],local_files_only=True);ids=p['cells']['C00']['tokens'].copy();assert t.encode('<|coord_998|>',add_special_tokens=False)==[152668];ids[5]=152668; history=p['common_history_ids']+ids
p['cells']['Y1_998']=dict(category='chair',y1=998,y2=999,text=t.decode(ids,skip_special_tokens=False,clean_up_tokenization_spaces=False),tokens=ids,history_ids=history,history_sha256=hashlib.sha256(json.dumps(history,sort_keys=True,separators=(',',':')).encode()).hexdigest(),edits=[dict(row_token_offset=5,old=152669,new=152668)])
p['active_cells']=['Y1_998'];p['inherited_cells'].append('Y998');p['controls']['Y998']={k:bind(old/f'runtime/Y998/{k}.json') for k in ['raw','receipt']}
p['sources'] += [bind(old/f) for f in ['panel.json','producer.py','reduce.py','result.json','terminal.json','lead-acceptance.json']]+list(p['controls']['Y998'].values())
p['schema']='corner_loop.y1_one_bin_control.v1';p['interpretation']='Same token pair at y1 versus y2 confounds slot role with validity boundary; one numerical bin is not small embedding distance. Stop local series after this cell.'
p['derivative']=dict(predecessor=bind(old/'producer.py'),executed=bind(r/'producer.py'),diff=bind(r/'producer.diff'),changes='root, cell choice and description only')
(r/'panel.json').write_text(json.dumps(p,indent=2,sort_keys=True)+'\n')
s=(old/'reduce.py').read_text().replace('runtime/Y998','runtime/Y1_998').replace('==[7]','==[5]').replace("ids'][7]","ids'][5]").replace('corner_loop.one_bin_control.result.v1','corner_loop.y1_one_bin_control.result.v1')
s=s.replace("controls=read(OLD/'result.json')['cells'];", "controls=dict(read(OLD/'result.json')['cells']);controls['Y998']=read(R.parent/'2026-09-16-corner-loop-one-bin-control/result.json')['cell'];")
(r/'reduce.py').write_text(s)
(r/'run.sh').write_text('#!/bin/bash\ncd /data/CoordExp/.worktrees/research-probes\nroot='+str(r)+'\nPYTHONPATH=. CUDA_VISIBLE_DEVICES=0 python "$root/producer.py" Y1_998 > "$root/Y1_998.log" 2>&1\ncode=$?\nprintf "%s\\n" "$code" > "$root/run.exit"\nexit "$code"\n')
u=Path('research/experiments')/r.name;u.mkdir()
(u/'unit.md').write_text('''# Final paired coordinate-substitution control\n\nFrom R16 at image477415 natural first136 rows, does the same coord_999→coord_998 substitution at y1 release useful free owner coverage, compared with accepted y2 Y998 and C00?\n\nPredecessors: category-only C10, geometry-only C01 and joint C11 recover the same16 owners transiently then relapse; accepted Y998 changes logits but reproduces all1851 C00 free tokens. This single cell finishes the local substitution series.\n\n## Frozen contract\n\nY1_998 supplies chair [0,998,999,999] at row137. Exactly row token offset5 / action offset1229 changes152669→152668. Common1224 tokens and nine-token row preserved. Totalcap3084,1851 unrestricted free tokens; no forced opener or EOS. Original heterogeneous bs4/order/left padding, FP32/SDPA/RP1, original prompt/media/MRoPE, R16 adapter and original embeddings are inherited through panel.json hashes. No GPU control reruns.\n\nThe panel binds original config/model/bank, literal histories, original companion sequences, C00/C01/C10/C11 and Y998 raw/receipts/results and the exact executed producer/consumer. No mutable research record is a source binding.\n\nUse the accepted pure consume function without rebinding. Exclude supplied137 from owner matching and free error counts. Preserve raw invalid rows, UNKNOWN semantics, one-to-one assignment, history/free identity and supplied-credit sensitivity. Primary outcome is all free owner identities and coverage, G/L/swaps/retention and comparison with recovered16, complete output burden, EOS/cap, recurrence and exact suffix identity. Inspect captured seam logits even for identical output. Tiny positive-height validity is determined by parser, not physical-owner meaning.\n\n## Budget and stopping\n\nOne scientific GPU cell, intended3084 native bs4 forward calls, absolute ceiling5000 including mechanical attempts, intended≤1800 allocated GPU-seconds. Only bounded repair of concrete mechanical conflict; otherwise BLOCKED. No extra rows/images/seeds/doses, training, labels/loss, embedding/KV changes, visual work, subagents, control sweep or automatic successor. Stop after one suffix and independent CPU reduction; candidate pending lead acceptance.\n\n## Asymmetric inference\n\nRecovery establishes slot-dependent sensitivity for this token pair and makes full-image extent unnecessary here, but cannot separate slot role from validity crossing. Failure means both tested one-bin edits insufficient at this boundary, not all small perturbations. Category-only success already refutes universal necessity of validity repair. Numerical distance does not measure embedding distance; neither outcome identifies embedding defects, KV malfunction or universal mechanism. Any future work requires a separately authorized, qualitatively different mechanism question.\n\nEvidence root: '''+str(r)+'\n')
state=dict(schema_version=1,unit_id=r.name,lifecycle='ready',evidence='none',disposition='frozen_single_y1_control',state_as_of='2026-09-16',protocol=str(u/'unit.md'),result=None,state_source=str(u/'unit.md'),boundary='One Y1_998 cell; inherited controls; supplied137 zero credit; final local substitution control.',not_authorized=['further controls or successor','training/labels/loss','embedding/KV edits','subagents'],next_action='Execute one frozen cell then reduce and stop.')
(u/'state.json').write_text(json.dumps(state,indent=2)+'\n')
cat=Path('research/experiments/catalog.jsonl');entry=dict(id=r.name,title='477415 R16 final paired y1 one-bin control',kind='experiment',topics=['history-repetition-stopping','greedy-compilation'],record_root=str(u),protocols=[str(u/'unit.md')],result_records=[],reading_entry=str(u/'unit.md'),tracking='current',state=str(u/'state.json'));cat.write_text(cat.read_text()+json.dumps(entry)+'\n')
idx=Path('research/index.md');idx.write_text(idx.read_text()+'\nFinal local substitution control: [Y1_998 unit](experiments/'+r.name+'/unit.md), [state](experiments/'+r.name+'/state.json). One frozen cell; stop after reduction, no automatic successor.\n')
(r/'prepare.py').write_text(Path(__file__).read_text())
print(p['cells']['Y1_998']['text']);print('sources verified',len(p['sources']))
