"""Small feature-space helpers for the visual-support counterfactual probe."""

from .intervention import (
    FeatureBundle,
    FeatureLayoutError,
    FeatureReplayController,
    FreshFeatureCaptureController,
    PixelBounds,
    VisualFeatureLayout,
    build_merged_support_mask,
    capture_feature_bundle,
    choose_deterministic_control_mask,
    prune_symmetric_translation_overlap,
    clone_feature_bundle,
    feature_bundle_fingerprint,
    compose_rgb_patch,
    file_sha256,
    load_rgb_uint8,
    materialize_rgb_uint8,
    rgb_array_sha256,
    replace_selected_indices,
    tensor_sha256,
    validate_equal_mask_shape_and_count,
    validate_feature_layout,
)

__all__ = [
    "FeatureBundle",
    "FeatureLayoutError",
    "FeatureReplayController",
    "FreshFeatureCaptureController",
    "PixelBounds",
    "VisualFeatureLayout",
    "build_merged_support_mask",
    "capture_feature_bundle",
    "choose_deterministic_control_mask",
    "prune_symmetric_translation_overlap",
    "clone_feature_bundle",
    "feature_bundle_fingerprint",
    "compose_rgb_patch",
    "file_sha256",
    "load_rgb_uint8",
    "materialize_rgb_uint8",
    "rgb_array_sha256",
    "replace_selected_indices",
    "tensor_sha256",
    "validate_equal_mask_shape_and_count",
    "validate_feature_layout",
]
