extends: ./a_only.yaml

training:
  run_name: epoch_2-eff_size_64-add_coord_ce-eval_vllm_colocate
  output_dir: output/stage2_ab/coco_bbox_max60/a_only_eval_vllm_colocate
  logging_dir: tb/stage2_ab/coco_bbox_max60/a_only_eval_vllm_colocate

rollout_matching:
  eval_rollout_backend: vllm
  vllm:
    mode: colocate
