extends: ../_shared/prod_ab_mixed_vllm.yaml

model:
  model: output/stage2_ab/coco_bbox_max60/a_only/epoch_2-eff_size_64-add_coord_ce-merged

training:
  run_name: eff_size_96-b_ratio_0.05-epoch_2
  artifact_subdir: stage2_ab/prod/ab_mixed

custom:
  val_sample_limit: 504
