extends:
  - ../lvis_bbox_max60_1024.yaml
  - ./common_prodlike.yaml

training:
  run_name: smoke_2steps-stage1-lvis_bbox_max60_1024-hard_ce_soft_ce_w1_ciou_bbox_size-adjrep_global0p01
  artifact_subdir: stage1/smoke/lvis_bbox_max60_1024_adjacent_repulsion_global
  static_packing_cache:
    root_dir: temp/static_packing_smoke/stage1_lvis_bbox_max60_1024_adjacent_repulsion_global

custom:
  eval_detection:
    limit: 8
