extends: a_only_iter1.yaml

# Override to use the 32x32x1024 COCO path and explicit budget.
model:
  #model: output/stage1/coco_bbox_max60-coco80-desc_first/epoch_4-softce_w1-coco80-ckpt_1832-merged
  model: output/stage2_ab/2b_1024/a_only_iter1/merged_ckpt-900
  
training:
  run_name: epoch_1-eff_size_128-n_softctx_iter_1-a_only
  output_dir: output/a_only/ciou_bbox_area/4b-softce_w1-coco80
  logging_dir: tb/a_only/ciou_bbox_area/4b-softce_w1-coco80
  num_train_epochs: 1
  effective_batch_size: 128

template:
  max_pixels: 1048576

custom:
  offline_max_pixels: 1048576
  train_jsonl: public_data/coco/rescale_32_1024_bbox_max60/train.coord.jsonl
  val_jsonl: public_data/coco/rescale_32_1024_bbox_max60/val.coord.jsonl
