extends: a_only_iter1-res_1024.yaml

model:
  model: /data/home/xiaoyan/AIteam/data/CoordExp/output/stage2_ab/2b_1024/a_only_iter1/merged_ckpt-900

training:
  seed: 17
  run_name: ablation_seed17_stage2_a_only_iter1_res1024_sorted_order
  output_dir: output/stage2_ab/ablation/a_only_iter1_res1024_sorted_order
  logging_dir: tb/stage2_ab/ablation/a_only_iter1_res1024_sorted_order
  encoded_sample_cache:
    enabled: false

custom:
  train_jsonl: /data/home/xiaoyan/AIteam/data/CoordExp/public_data/coco/rescale_32_1024_bbox_max60/train.coord.jsonl
  val_jsonl: /data/home/xiaoyan/AIteam/data/CoordExp/public_data/coco/rescale_32_1024_bbox_max60/val.coord.jsonl
  object_ordering: sorted
