import datetime,hashlib,json,pathlib,os,shutil
R=pathlib.Path(__file__).parent;U=pathlib.Path('/data/CoordExp/.worktrees/research-probes/research/experiments/2026-09-18-owner-recurrence-onset');REPO=U.parents[2]
read=lambda p:json.loads(pathlib.Path(p).read_text())
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
def bind(p):return dict(path=str(p),sha256=hashlib.sha256(p.read_bytes()).hexdigest(),size_bytes=p.stat().st_size)
assert not (R/'lead-acceptance.json').exists()
d=read(R/'reduction.json');p=read(R/'panel.json');rec=[read(R/f'runtime/{m}/receipt.json') for m in ['native','scores']];assert read(R/'independent-verification.json')['status']=='passed';assert all(not pathlib.Path('/proc',str(x['pid'])).exists() for x in rec);assert all((R/f'{m}.exit').read_text().strip()=='0' for m in ['native','scores'])
summary={}
for name,w in d['windows'].items():
 summary[name]=dict(row=w['row'],action_offset=w['offset'],conditioning=w['conditioning'],row_logprobs={k:v['sum_logprob'] for k,v in w['candidates'].items()},forks=w['forks'])
cost=dict(model_forwards=sum(x['model_forwards'] for x in rec),vision_forwards=sum(x['vision_forwards'] for x in rec),allocated_gpu_seconds=sum(x['elapsed_seconds'] for x in rec),peak_reserved_bytes=max(x['peak_reserved_bytes'] for x in rec),tensor_bytes=sum(f.stat().st_size for f in (R/'runtime').rglob('*.pt')),successful_native_batches=1,candidate_full_prefix_calls=16,failed_attempts=1,failed_model_forwards=0,new_target_images=[417044])
assert cost['model_forwards']==3100 and cost['allocated_gpu_seconds']<10800 and cost['tensor_bytes']<1073741824
result=dict(schema='owner_recurrence_onset.result.v1',status='candidate_complete',technical_status='exact native replay and margin-relevant full-prefix parity passed',scientific_status='finite coherent-row preference for repeated owner; local coordinate norm sensitivity without A/B pair reversal',panel=bind(R/'panel.json'),reduction=bind(R/'reduction.json'),independent_verification=bind(R/'independent-verification.json'),physical_admission=d['admission'],windows=summary,parity=dict(comparisons=len(d['native_parity']),max_abs=max(x['max_abs'] for x in d['native_parity']),max_twice_error_over_margin=max(x['twice_error_over_margin'] for x in d['native_parity']),max_readout_reconstruction_error=max(x['max_abs'] for x in d['reconstruction'])),current_matches={k:dict(count=v['current63']['matches']['matched_count'],owner_ids=v['current63']['matches']['covered_owner_ids'],FN=63-v['current63']['matches']['matched_count'],burden=v['current63']['burden']) for k,v in d['scoring'].items()},cost=cost,limits=['Row4 earliest possible recurrence identity HOLD; row6 earliest confirmed under9-row inspection','Two realizations per owner; not owner probability, exhaustive search or all likelihood optima','Normal comparator uses saved norm target history with original companions; history geometry/order/length differ','Offline equal norm changes x1 winner to30, not supported B52/57; no free continuation tested','R16 includes ranking; no pure-SFT or training-origin conclusion','63 positive annotations have no explicit ignore semantics; unmatched UNKNOWN','No selective upstream query/key/value mechanism identified'],not_executed=['351017 control','7116 control','repair rollout','Q/K/V/layer captures'],recommendation='If root needs a next causal decision, test the single measured recurrence x1 0→30 choice followed by original greedy, with original trajectory control and owner retention/debt; do not infer sufficiency from this offline rank reversal.',live_owned_jobs=[],cleanup=[])
write(R/'result.json',result)
