"""Reusable contracts for spatial-scope and history-disentanglement research."""

from src.analysis.spatial_scope_history._review_finalization import (
    ADJUDICATOR_DECISION_SCHEMA_VERSION,
    FinalReviewLedgerArtifacts,
    assemble_final_review_ledger,
    build_bound_adjudication_queue,
)

from src.analysis.spatial_scope_history.cohort_ledger import (
    AttemptDependencyContract,
    AttemptLedger,
    AttemptRecord,
    CohortImageRecord,
    CohortLedger,
    ExecutionIdentityBundle,
    append_attempt_record,
    dependency_skip_failure_code,
    dependency_state_unavailable_failure_code,
)
from src.analysis.spatial_scope_history.schedule import (
    BlockedDependency,
    DecodeProvenance,
    DeferredDependency,
    GridProvenance,
    PRIMARY_ARM_CODES,
    PhysicalBatchDefinition,
    PhysicalBatchPlan,
    RequestBatch,
    ResearchSchedule,
    ResumePlan,
    ScheduledRequest,
    derive_sampling_seed,
    primary_arm_definition,
)
from src.analysis.spatial_scope_history.execution_evidence import (
    ExecutionEvidenceEnvelope,
    TerminalCallOutputBundle,
)

from src.analysis.spatial_scope_history.spatial import (
    MaterializedVisualInput,
    SpatialCell,
    SpatialCoordinateReceipt,
    SpatialGrid,
    SpatialGridSpec,
    SpatialImageEncoding,
    SpatialOwnership,
    SpatialProcessorReceipt,
    SpatialVariantPlan,
    VisualInputMaterializationReceipt,
    spatial_variant_mode_for_arm,
)

__all__ = [
    "AttemptDependencyContract",
    "AttemptLedger",
    "AttemptRecord",
    "ADJUDICATOR_DECISION_SCHEMA_VERSION",
    "BlockedDependency",
    "CohortImageRecord",
    "CohortLedger",
    "DecodeProvenance",
    "DeferredDependency",
    "ExecutionIdentityBundle",
    "ExecutionEvidenceEnvelope",
    "FinalReviewLedgerArtifacts",
    "GridProvenance",
    "MaterializedVisualInput",
    "PRIMARY_ARM_CODES",
    "PhysicalBatchDefinition",
    "PhysicalBatchPlan",
    "RequestBatch",
    "ResearchSchedule",
    "ResumePlan",
    "ScheduledRequest",
    "SpatialCell",
    "SpatialCoordinateReceipt",
    "SpatialGrid",
    "SpatialGridSpec",
    "SpatialImageEncoding",
    "SpatialOwnership",
    "SpatialProcessorReceipt",
    "SpatialVariantPlan",
    "TerminalCallOutputBundle",
    "VisualInputMaterializationReceipt",
    "append_attempt_record",
    "assemble_final_review_ledger",
    "build_bound_adjudication_queue",
    "dependency_skip_failure_code",
    "dependency_state_unavailable_failure_code",
    "derive_sampling_seed",
    "primary_arm_definition",
    "spatial_variant_mode_for_arm",
]
