"""One-shot candidate closeout; never run after lead acceptance."""
import json,hashlib,datetime,shutil
from pathlib import Path
R=Path(__file__).resolve().parent;W=Path('/data/CoordExp/.worktrees/research-probes');U=W/'research/experiments'/R.name
assert not (R/'lead-acceptance.json').exists()
read=lambda p:json.loads(p.read_text())
bind=lambda p:dict(path=str(p.resolve()),sha256=hashlib.sha256(p.read_bytes()).hexdigest(),size_bytes=p.stat().st_size)
d=read(R/'factorial-decision.json');cost=read(R/'cost.json');reduction=read(R/'reduction.json');rest=read(R/'restoration.json');ind=read(R/'independent-output-check.json')
assert d['selected_specificity'] is None and rest['status']=='passed' and ind['status']=='passed' and cost['owned_live_jobs']==[]
f=d['factorial'];effects={n:f[n]['fork']['coord131_minus_coord0']-f[b]['fork']['coord131_minus_coord0'] for n,b in [('W','F'),('RW','R'),('HW','H'),('RHW','RH')]}
claims=[
 'The contextual wrapper changes the measured decision margin with literal wrapper tokens and positions held fixed; none of the three non-restoration W-on conditions changes the immediate winner or gains a current-positive free owner.',
 'Only R+H+W changes coord0 to coord131. It exactly reconstructs native-S layer20 and the accepted R20 intervention head/logits. This expected all-source restoration is mechanics evidence, not a selective wrapper mechanism.',
 'RHW ends at154 tokens with three current-positive free matches and zero free invalid/malformed/strict/literal repeats. Its entire four-member output equals the accepted original-cache rebuild from the same first68 tokens; additional retained current cache has no observed output effect on this route.',
 'W has the exact native-F full output despite changed current cache. RW and HW retain the same first68 tokens but later differ from the exact original-cache rebuild at offsets114 and248; both cap without current-positive recovery. Retained-state effects are route-dependent and can be unhelpful.',
 'Close this selected branch as mixed-state dependence. No non-restoration specificity gate passes; F2 and additional GPU rebuilds are unexecuted, not negative results.'
]
limits=[
 'One selected bird/image309264, one S/F pair, one decision and layers14..20; no population or cross-case mechanism claim.',
 'Generic donor compatibility/distributed contextual information remains the strongest alternative; restoration does not identify native information origin, a ledger, semantic owner binding or a specialized wrapper circuit.',
 'Current-positive annotation version has14 bird boxes and no explicit ignore masks. Unmatched and removed labels remain UNKNOWN, not physical negatives. Supplied identity uncertainty remains; no seven-owner credit is inherited.',
 'Primary begins after complete intervention-generated row at72. The current-positive supplied union is empty, so primary denominator14; native-F future retention denominator is0, making retention uninformative rather than perfect.',
 'RHW has six unmatched valid free predictions requiring unresolved physical identity/extent interpretation. Zero strict repeats does not prove zero physical recurrence or precise/exhaustive enumeration.',
 'Conditional intervention recovery is not empty-prefix greedy improvement, learned repair, training-origin evidence or deployment promotion.'
]
result=dict(status='candidate',technical_status='passed',scientific_status='mixed-state dependence; no selective partial-source recovery',unit=R.name,protocol=bind(R/'source-snapshots/unit.md'),executed_producer=bind(R/'source-snapshots/wrapper_history.py'),predecessor_acceptance=bind(R.parent/'2026-09-17-history-rereading-mechanism/lead-acceptance.json'),factorial=f,wrapper_margin_effect=effects,restoration=rest,rebuild_reuse=d['rebuild_reuse'],claims=claims,limits=limits,annotation=dict(version='annotation-snapshot-v1',image309264_current_positive_count=14,explicit_ignore_fields=False,supplied_union=[],native_future_retention_denominator=0,bindings=[bind(R.parent/'2026-09-17-history-rereading-mechanism/human-evaluation/annotation-snapshot-v1/working.norm.jsonl'),bind(R.parent/'2026-09-17-history-rereading-mechanism/human-evaluation/evaluation-v1/result.json')]),conditional=dict(F2='not admitted: no qualifying partial effect',new_rebuilds='not needed: exact coord0/coord131 controls reused and full suffixes compared',failed_cells=[],HOLD=['physical identities of unmatched predictions; no negative inference'],unexecuted=['F2 capture','F2 W specificity','additional native rebuilds']),cost=cost,verification=[bind(R/x) for x in ['cpu-check.json','verify-native-F-self-F.json','verify-W-RW-HW-RHW.json','restoration.json','independent-output-check.json','factorial-decision.json']],hypotheses=[dict(account='Distributed contextual compatibility across entering state and paired history',evidence='All-source reconstruction exact; partial margins shift but do not win',status='strongest surviving explanation, not unique'),dict(account='Selective contextual wrapper source sufficient for recovery',evidence='W/RW/HW fail useful recovery at this fixed decision',status='not supported here; global absence not established'),dict(account='Token-only account for every intervention',evidence='RW/HW same first68 but retained-cache drift; rebuild removes drift',status='insufficient globally; sufficient for measured RHW output'),dict(account='Unique repetition/owner ledger circuit',evidence='No selective partial source, F2 gate closed',status='unidentified')],recommendation='Stop this factor-decomposition branch. No precise selective-wrapper cross-case prediction is yet supported. If root chooses a qualitatively different confirmation question,417044 is the named first candidate with frozen63 current positives; do not automatically rerun this restoration factorial there.',cleanup=dict(deleted_paths=[],deleted_bytes=0),owned_live_jobs=[],worker_status='existing row_factor/state_patch completed; no new agents')
(R/'result.json').write_text(json.dumps(result,indent=2)+'\n')
lines=['# Wrapper-history factorial — candidate','', 'Technical acceptance passed; scientific result: mixed-state dependence without selective partial-source recovery. Root acceptance is pending.','', '| Factors | 131−0 margin | Rank131 | Winner | Current free matches /14 | Free invalid / malformed | Strict / literal repeats | Stop / total tokens |','|---|---:|---:|---|---:|---|---|---|']
for n in ['F','R','H','RH','W','RW','HW','RHW']:
 c=f[n];b=c['burden'];lines.append(f"| {n} | {c['fork']['coord131_minus_coord0']:.6f} | {c['fork']['competitors']['151801']['rank']} | coord{c['fork']['argmax']-151670} | {len(c['primary']['free'])} | {b['invalid']} / {b['malformed']} | {b['strict_valid_repeats']} / {b['literal_repeats']} | {c['stop']} / {c['tokens']} |")
lines+=['','R is donor current state after layer13; H is supplied-row cache54..62; W is contextual wrapper cache63..65. All paired historical substitutions occur at action67/layers14..20 and are restored after attention. Current-position cache can persist.','', '## Findings','']+[f'- {x}' for x in claims]
lines+=['','The W margin effects under F/R/H/RH are '+', '.join(f'{effects[k]:+.6f}' for k in ['W','RW','HW','RHW'])+'. These are selected conditional effects, not causal percentages. EOS remained a low-ranked competitor at the fork (ranks retained in the result).','', 'RHW free current-positive IDs:367404,41529,42098; FN11/14. Every other factorial cell has0 and FN14/14. The empty current-positive supplied union and zero native-future retention denominator are explicit. Annotation match is not a complete physical owner census.','', '## Limits and decision','']+[f'- {x}' for x in limits]
lines+=['',result['recommendation'],'','## Evidence and cost','',f"Six new native batches, {cost['model_forwards']} forwards, {cost['allocated_GPU_seconds']:.2f} allocated GPU-seconds, {cost['elapsed_execution_seconds']} execution seconds; {cost['tensor_bytes']} tensor bytes. No failures, live owned jobs, cleanup, training or new F2/rebuild GPU work.",'',f"Artifact map: `{R}/ARTIFACTS.md`. Frozen protocol: `{R}/source-snapshots/unit.md`. Candidate result: `{R}/result.json`. Independent JSON-exact saved-token reconstruction and separate token geometry/repeat counting: `{R}/independent-output-check.json`. Native/self, target/companion, source-position, history restoration and expected donor restoration checks passed exactly. Original outputs and accepted annotations remain unchanged."]
(U/'results.md').write_text('\n'.join(lines)+'\n')
s=read(U/'state.json');s.update(lifecycle='closed',evidence='unreviewed',disposition=result['scientific_status'],state_as_of=datetime.datetime.now(datetime.timezone.utc).isoformat(),result=f'research/experiments/{R.name}/results.md',state_source=f'research/experiments/{R.name}/results.md',next_action='Root independent acceptance; no worker successor authorized.');(U/'state.json').write_text(json.dumps(s,indent=2)+'\n')
cat=W/'research/experiments/catalog.jsonl';lines=cat.read_text().splitlines()
for i,line in enumerate(lines):
 x=json.loads(line)
 if x.get('id')==R.name:
  x['result_records']=[f'research/experiments/{R.name}/results.md'];x['reading_entry']=x['result_records'][0];lines[i]=json.dumps(x)
cat.write_text('\n'.join(lines)+'\n')
(R/'candidate-records').mkdir(exist_ok=True)
for name in ['unit.md','results.md','state.json']:shutil.copy2(U/name,R/'candidate-records'/name)
print(json.dumps(dict(status='candidate',forwards=cost['model_forwards'],claims=len(claims))))
