extends:
  - ./coord_soft_ce_gate_coco80_desc_first.yaml
  - ../../../_shared/datasets/coco_1024_bbox_max60_lvis_proxy.yaml

model:
  model: output/stage1/coco_bbox_max60-coco80-desc_first/epoch_4-softce_w1-coco80-ckpt_1832-merged

training:
  num_train_epochs: 2
  artifact_subdir: stage1/coco_bbox_max60-coco80-desc_first-1024-lvis_proxy
  run_name: epoch_2-continue-from-4b
