template:
  max_pixels: 1048576

custom:
  offline_max_pixels: 1048576
  train_jsonl: public_data/coco/rescale_32_1024_bbox_max60/train.coord.jsonl
  val_jsonl: public_data/coco/rescale_32_1024_bbox_max60/val.coord.jsonl
  object_ordering: sorted
