"""Native Qwen/CoordExp special-token constants."""

OBJECT_REF_START_TOKEN = "<|object_ref_start|>"
OBJECT_REF_END_TOKEN = "<|object_ref_end|>"
BOX_START_TOKEN = "<|box_start|>"
BOX_END_TOKEN = "<|box_end|>"
COORD_WILDCARD_TOKEN = "<|coord_*|>"
COORD_START_TOKEN = "<|coord_0|>"
COORD_END_TOKEN = "<|coord_999|>"

EXPECTED_OBJECT_REF_START_ID = 151646
EXPECTED_OBJECT_REF_END_ID = 151647
EXPECTED_BOX_START_ID = 151648
EXPECTED_BOX_END_ID = 151649
EXPECTED_COORD_WILDCARD_ID = 151669
EXPECTED_COORD_START_ID = 151670
EXPECTED_COORD_END_ID = 152669

__all__ = [
    "OBJECT_REF_START_TOKEN",
    "OBJECT_REF_END_TOKEN",
    "BOX_START_TOKEN",
    "BOX_END_TOKEN",
    "COORD_WILDCARD_TOKEN",
    "COORD_START_TOKEN",
    "COORD_END_TOKEN",
    "EXPECTED_OBJECT_REF_START_ID",
    "EXPECTED_OBJECT_REF_END_ID",
    "EXPECTED_BOX_START_ID",
    "EXPECTED_BOX_END_ID",
    "EXPECTED_COORD_WILDCARD_ID",
    "EXPECTED_COORD_START_ID",
    "EXPECTED_COORD_END_ID",
]
