"""Compact detection structural marker identity."""

from src.tokens.qwen_native import (
    BOX_START_TOKEN,
    EXPECTED_BOX_START_ID,
    EXPECTED_OBJECT_REF_START_ID,
    OBJECT_REF_START_TOKEN,
)

COMPACT_STRUCTURE_TOKENS = (OBJECT_REF_START_TOKEN, BOX_START_TOKEN)
EXPECTED_COMPACT_STRUCTURE_IDS = {
    OBJECT_REF_START_TOKEN: EXPECTED_OBJECT_REF_START_ID,
    BOX_START_TOKEN: EXPECTED_BOX_START_ID,
}

__all__ = ["COMPACT_STRUCTURE_TOKENS", "EXPECTED_COMPACT_STRUCTURE_IDS"]
