"""Parent synthesis of the fixed emitted-choice by continuing-readout factorial."""
import json,hashlib,datetime,csv
from pathlib import Path
R=Path('/data/CoordExp/outputs/research/qwen3-vl-dense-enumeration/2026-09-19-first-coordinate-mediation');U=Path('research/experiments/2026-09-19-first-coordinate-mediation')
def bind(p):return dict(path=str(p.resolve()),sha256=hashlib.sha256(p.read_bytes()).hexdigest())
def main():
 d=json.loads((R/'reduction.json').read_text());v=json.loads((R/'verification.json').read_text());p=json.loads((R/'execution-plan.json').read_text());bv=json.loads((R/'binding-verification.json').read_text());q=json.loads((R/'runtime/qualification/qualification-receipt.json').read_text());s=json.loads((R/'runtime/scaleout-receipt.json').read_text());assert d==json.loads((R/'reduction-recheck.json').read_text());assert len(d['cells'])==v['cells']==36;assert sum(c['control_equal'] is True for c in d['cells'])==18;assert not bv['unresolved']
 failures=[]
 for lp in (R/'runtime/failed-precreate-v1').glob('*/live.json'):
  x=json.loads(lp.read_text());failures.append(dict(path=str(lp),seconds=x['ended_at_unix']-x['runtime_started_at_unix'],exit_code=x['exit_code']))
 failed_seconds=sum(x['seconds'] for x in failures);cost=dict(model_forwards=q['model_forwards']+s['model_forwards_total'],successful_runtime_gpu_seconds=q['gpu_seconds']+s['gpu_seconds_total'],zero_forward_failed_launch_wall_seconds=failed_seconds,budget_charged_seconds=q['gpu_seconds']+s['gpu_seconds_total']+failed_seconds,tensor_bytes=q['tensor_bytes']+s['tensor_bytes_total'],failed_launches=failures);now=datetime.datetime.now(datetime.timezone.utc).isoformat()
 with (R/'outcomes.csv').open('w') as f:
  names=['model','policy','forced_choice','primary_near_run','primary_exact_run','primary_invalid','primary_rows','stop','first_row_values','first_row_valid','whole_near_run','whole_rows'];w=csv.DictWriter(f,fieldnames=names);w.writeheader()
  for c in d['cells']:
   m=c['primary'];whole=c['whole_including_controlled_row'];first=c['first_partially_controlled_row'];w.writerow(dict(model=c['model'],policy=c['policy'],forced_choice=c['forced_choice'],primary_near_run=m['longest_near_run'],primary_exact_run=m['longest_exact_run'],primary_invalid=m['invalid_rows'],primary_rows=m['complete_rows'],stop=c['stop'],first_row_values=first['values'] if first else None,first_row_valid=first['valid'] if first else None,whole_near_run=whole['longest_near_run'],whole_rows=whole['complete_rows']))
 scientific='First x1=1 is sufficient for a low-recurrence conditional original-readout route in untied donut, but not tied donut. It is not necessary for the numerical effect of sign20/22/23/24 in either model: all remain near-run1 when first x1 is forced0. Continuing readout can act through other choices; the post-hoc first-token association is not a complete mediator.'
 result=dict(status='INTEGRATED_CANDIDATE',acceptance='unreviewed_by_root',unit=U.name,created_at=now,scientific=scientific,technical='36/36 cells;18 exact concordant controls;11248 savedsteps verify onlyoffset5override and native subsequenttokenconsumption.',cost=cost,unsupported=[],physical_status='not_established',limits=['Primary metrics exclude the entire first completed partiallycontrolledrow. Whole metrics remain separately labeled.','Outcome-selected two-model single-image follow-up, not prevalence or held-out efficacy.','Near-row recurrence is a numerical proxy; EOS/fewer rows/another pattern is not physical recovery.','Continuing readout changes many coordinate logits. Several bins share signpatterns; no bin0 coefficient uniqueness or universal circuit claim.','T/U compares mature model packages; no untie-only or training-origin conclusion.','Target outputs only; companions outside estimand.'],failures='Eight launch wrappers pre-created output directories and failed before model loading/forward. Evidence preserved; wrapper corrected once,32 remainingcells executed once. Pre-launch role guard corrected before anyGPU calls; CPU gate catches wrongoffset/token. No producer failure or scientific cell omission.',evidence=[bind(R/n) for n in ['execution-plan.json','reduction.json','verification.json','binding-verification.json','continued-readout-forks.json','outcomes.csv','ARTIFACTS.md']],live_jobs=[])
 (R/'result.json').write_text(json.dumps(result,indent=2)+'\n')
 lines=['# First-coordinate mediation','',f'Candidate completed {now}; root acceptance pending.','',scientific,'','## Fixed evidence','','Both mature donut417044 original failure histories were crossed with original/sign19–26 readout and forced first x1=0/1. All36 cells completed. All18 concordant controls exactly reproduce accepted source sequences. Independent CPU reduction is JSON-exact; saved head/logit/carrier traces verify11,248 steps, exactly one offset5 override percell, and forced-token consumption at offset6. CPU corruption checks reject wrong forced position and wrong token.','', 'The following outcomes use **only fully free rows after the first completed row**. Each entry is longest near-run / invalid rows / free rows / stop; R means32 whole rows (31 primary rows), E means naturalEOS. First-row geometry/validity and whole-sequence exact/near/native/alternate metrics are retained in `reduction.json` and `outcomes.csv`.','', '| Model | Readout | First x1=0 | First x1=1 |','|---|---|---|---|']
 for model in ['tied','untied']:
  for policy in p['policies']:
   cc={c['forced_choice']:c for c in d['cells'] if c['model']==model and c['policy']==policy}
   def fmt(k):
    c=cc[k];m=c['primary'];return f"{m['longest_near_run']}/{m['invalid_rows']}/{m['complete_rows']}/{'E' if c['stop']=='eos' else 'R'}"
   lines.append(f'| {model} | {policy} | {fmt(0)} | {fmt(1)} |')
 lines+=['','All first rows are complete and geometrically valid; all primary/whole malformed-opener counts are zero and no512-token cap occurs. Validity does not establish physical identity. No controlled row receives recovery credit.','', '## Interpretation and remaining alternatives','','- **Untied original:** changing only emitted first x1 from0 to1 changes primary longest near-run13→1, with29 free rows thenEOS instead of31 free rows at the whole32-row limit. This establishes conditional sufficiency for that numerical route, with termination and physical coverage limits.','- **Tied original:** the same change gives17→19, both at31 free rows and one invalid row. The choice is not sufficient across these two model packages.','- **All four association-positive fields, both models:** forcing first x1=0 still yields primary near-run1. Initial x1=1 is therefore not necessary for their low-recurrence outcome here. Other first-row slots or later readout decisions provide alternate routes.','- **Concrete later route:** untied sign23/sign24 forced0 preserve the entire first-row token sequence of original0. Their first subsequent difference is offset15, the next row x1, where they emit1 instead of0. Other positive fields already differ at first-row x2/y2. This locates observed alternate decisions, not a unique causal circuit or proof a later single token is sufficient.','- **Other fields retained:** sign19/21/25/26 remain recurrent under both first choices, with geometry debt in some cases. The first choice does not erase continuing-readout effects.','', '## Technical closure','',result['failures'],'',f"Measured successful runtime: {cost['successful_runtime_gpu_seconds']:.3f} GPU-seconds. Conservatively adding {failed_seconds:.3f} seconds of eight pre-model failed launch intervals gives {cost['budget_charged_seconds']:.3f} budget-charged seconds ({cost['budget_charged_seconds']/3600:.3f} GPU-hours). Total {cost['model_forwards']:,} forwards and {cost['tensor_bytes']:,} tensor bytes; all8 GPUs used. Pilot and8 successful scaleout wrappers have observed0 exits; failed pre-model wrappers have observed1 exits. All owned jobs and Luna-max child ended.211 unique bindings verify with no unresolved gap.",'', 'An idle-child dispatch delay occurred before qualification; it consumed no model calls and duplicated no work. Root-owned catalog result registration is the only expected knowledge-check gap. Predecessors remain immutable. Exact artifacts/reproduction: `'+str(R/'ARTIFACTS.md')+'`.','', '## Claim boundaries','']+[f'- {x}' for x in result['limits']]
 (U/'results.md').write_text('\n'.join(lines)+'\n');st=json.loads((U/'state.json').read_text());st.update(lifecycle='closed',evidence='unreviewed',state_as_of=now,disposition=scientific,result=str(U/'results.md'),state_source=str(U/'results.md'),next_action='Root independent acceptance; worker stops. No successor.');(U/'state.json').write_text(json.dumps(st,indent=2)+'\n');print(json.dumps(dict(result=str(R/'result.json'),cost=cost)))
if __name__=='__main__':main()
